miTms/WebApp/Controllers/AccountManageController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using WebApp.Models;
 
using System.Collections.Generic;
using Newtonsoft.Json;
using WebApp.Services;

namespace WebApp.Controllers
{
    // [Authorize]
    public class AccountManageController : Controller
    {
        private ApplicationUserManager _userManager;
        private readonly ICompanyService _companyService;
        

        public AccountManageController()
        {
        }

        public AccountManageController(ApplicationUserManager userManager,
                                   ApplicationSignInManager signInManager,
                                   ICompanyService companyService

                                   )
        {
            //UserManager = userManager;
            //SignInManager = signInManager;
            _companyService = companyService;
            
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private ApplicationSignInManager _signInManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set { _signInManager = value; }
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ResetPassword(string id,string newPassword) {
           var code =  this.UserManager.GeneratePasswordResetToken(id);
           var result= this.UserManager.ResetPassword(id, code, newPassword);
           return Json(result, JsonRequestBehavior.AllowGet); 
        }
        [HttpGet]
        public ActionResult GetData(int page = 1, int rows = 10, string sort = "Id", string order = "desc", string filterRules = "")
        {
            var filters = JsonConvert.DeserializeObject<IEnumerable<filterRule>>(filterRules);
            int totalCount = 0;

            var users = this.UserManager.Users.OrderByName(sort, order);
            if (filters != null)
            {
                foreach (var filter in filters)
                {
                    if (filter.field == "UserName")
                    {
                        users = users.Where(x => x.UserName.Contains(filter.value));
                    }
                    if (filter.field == "Email")
                    {
                        users = users.Where(x => x.Email.Contains(filter.value));
                    }
                    if (filter.field == "PhoneNumber")
                    {
                        users = users.Where(x => x.PhoneNumber.Contains(filter.value));
                    }
                }
            }
            totalCount = users.Count();
            var datalist = users.Skip((page - 1) * rows).Take(rows);
            var datarows = datalist.Select(n => new {
                Id = n.Id,
                UserName = n.UserName,
                FullName = n.FullName,
                Gender = n.Gender,
                CompanyCode = n.CompanyCode,
                CompanyName = n.CompanyName,
                AccountType = n.AccountType,
                Email = n.Email,
                PhoneNumber = n.PhoneNumber,
                AvatarsX50 = n.AvatarsX50,
                AvatarsX120 = n.AvatarsX120,
                AccessFailedCount = n.AccessFailedCount,
                LockoutEnabled = n.LockoutEnabled,
                LockoutEndDateUtc = n.LockoutEndDateUtc,
                IsOnline=n.IsOnline,
                EnabledChat=n.EnabledChat }).ToList();
            var pagelist = new { total = totalCount, rows = datarows };
            return Json(pagelist, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetCompanyData()
        {
            var data = new List<CompanyViewModel>();
            var query = _companyService.Queryable().Select(x => new CompanyViewModel() { CompanyCode = x.Id.ToString(), CompanyName = x.Name, Type = 0 });

            data.AddRange(query);

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult SaveData(UserChangeViewModel users)
        {
            if (users.updated != null)
            {
                foreach (var item in users.updated)
                {
                    var user = UserManager.FindById(item.Id);
                    user.UserName = item.UserName;
                    user.Email = item.Email;
                    user.FullName = item.FullName;
                    user.CompanyCode = item.CompanyCode;
                    user.CompanyName = item.CompanyName;
                    user.AccountType = item.AccountType;
                    user.PhoneNumber = item.PhoneNumber;
                    user.EnabledChat = item.EnabledChat;
                    user.Gender = item.Gender;
                    var result = UserManager.Update(user);

                }
            }
            if (users.deleted != null)
            {
                foreach (var item in users.deleted)
                {
                    var user = UserManager.FindByEmail(item.Email);
                    var result = UserManager.Delete(user);
                }
            }
            if (users.inserted != null)
            {
                foreach (var item in users.inserted)
                {
                    var user = new ApplicationUser
                    {
                        UserName = item.UserName,
                        Email = item.Email,
                        FullName = item.FullName,
                        Gender = item.Gender,
                        CompanyCode = item.CompanyCode,
                        CompanyName = item.CompanyName,
                        PhoneNumber = item.PhoneNumber,
                        AccountType = item.AccountType
                    };
                    var result = UserManager.Create(user, "123456");
                }
            }


            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    //await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "AccountManager");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {

            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return View("Error");
            }

            return View(user);

        }

        [HttpPost]
        public async Task<ActionResult> Edit(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                var item = await UserManager.FindByIdAsync(user.Id);
                item.UserName = user.UserName;
                item.PhoneNumber = user.PhoneNumber;
                item.Email = user.Email;
                var result = await UserManager.UpdateAsync(item);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "AccountManager");
                }
                AddErrors(result);
            }
            return View(user);

        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(id);
                var result = await UserManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    if (Request.IsAjaxRequest())
                    {
                        return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                    }
                    return RedirectToAction("Index", "AccountManager");
                }
                AddErrors(result);
            }
            return View();
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {

miTms/WebApp/Views/AccountManage/Create.cshtml
@using WebApp.Models

@model RegisterViewModel

@{
    ViewBag.Title = "Create";
}




<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Category
                <small>Create</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>  @Html.ActionLink("Home", "Index", "Home")
                </li>
                 <li>
                    <i class="fa fa-folder-open"></i>  @Html.ActionLink("Users", "Index", "AccountManage")
                </li>
                <li class="active">
                    <i class="fa fa-file"></i> Create
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
     <div class="row">
        <div class="col-lg-12">

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <fieldset>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>
             
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="Create" />
                </div>
            </div>
        </fieldset>
         
    </div>
}

 </div>
</div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

miTms/WebApp/Views/AccountManage/Edit.cshtml
@using WebApp.Models

@model ApplicationUser

@{
    ViewBag.Title = "Edit";
}




<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                User
                <small>Edit</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>  @Html.ActionLink("Home", "Index", "Home")
                </li>
                 <li>
                    <i class="fa fa-folder-open"></i>  @Html.ActionLink("Users", "Index", "AccountManage")
                </li>
                <li class="active">
                    <i class="fa fa-file"></i> Edit
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
     <div class="row">
        <div class="col-lg-12">

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <fieldset>
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
             
             
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="Create" />
                </div>
            </div>
        </fieldset>
         
    </div>
}

 </div>
</div>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

miTms/WebApp/Views/AccountManage/_ResetPasswordPartial.cshtml
<div class="modal fade" id="resetpasswordModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">重置密码</h4>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-xs-12 col-sm-12 ">
                        <form id="resetpassword-form" class="smart-form client-form" novalidate>
                            <fieldset>
                                <section>
                                    <label class="input">
                                        <i class="icon-append fa fa-user"></i>
                                        <input type="text" name="rusername" placeholder="Username" id="rusername" autocomplete="off" value="">
                                        <input type="hidden" id="ruserid" name="ruserid" value="" />
                                        <b class="tooltip tooltip-bottom-right">(Optional) Used to display the profile name on the website</b>
                                    </label>
                                </section>
                                <section>
                                    <label class="input">
                                        <i class="icon-append fa fa-lock"></i>
                                        <input type="password" name="rpassword" placeholder="New password" id="rpassword" autocomplete="off">
                                        <b class="tooltip tooltip-bottom-right">Don't forget your password</b>
                                    </label>
                                </section>
                                <section>
                                    <label class="input">
                                        <i class="icon-append fa fa-lock"></i>
                                        <input type="password" name="rpasswordConfirm" id="rpasswordConfirm" placeholder="Confirm new password" autocomplete="off">
                                        <b class="tooltip tooltip-bottom-right">Don't forget your password</b>
                                    </label>
                                </section>
                            </fieldset>
                        </form>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    取消
                </button>
                <button type="button" onclick="setpassword()" class="btn btn-primary">
                    重置密码
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<script type="text/javascript">
    var $resetForm = {};
    $(function () {
        $resetForm = $("#resetpassword-form").validate({

            // Rules for form validation
            rules: {
                rusername: {
                    required: true
                },

                rpassword: {
                    required: true,
                    minlength: 3,
                    maxlength: 20
                },
                rpasswordConfirm: {
                    required: true,
                    minlength: 3,
                    maxlength: 20,
                    equalTo: '#rpassword'
                }

            },

            // Messages for form validation
            messages: {
                rusername: {
                    required: 'Please enter your user name'
                },

                rpassword: {
                    required: 'Please enter your password'
                },
                rpasswordConfirm: {
                    required: 'Please enter your password one more time',
                    equalTo: 'Please enter the same password as above'
                }

            },

            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });
    });
    

    function showresetform(userid, username) {
        $('#rusername').val(username);
        $('#ruserid').val(userid);
        console.log(userid);
        $('#resetpasswordModal').modal('toggle');
    }
    function setpassword() {
        if ($resetForm.valid()) {
            var id = $('#ruserid').val();
            var password = $('#rpassword').val();
            var url = "/AccountManage/ResetPassword?id=" + id + "&newPassword=" + password;

            $.get(url, function (res) {
                console.log(res);
                if (res.Succeeded) {
                    $('#resetpasswordModal').modal('toggle');
                } else {
                    $.messager.alert("错误",res.Errors[0])
                }
            });
           
        }

    }
</script>